- name: Install font packages
  kewlfft.aur.aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - all-repository-fonts
    - otf-font-awesome
    - ttf-fira-code
    - ttf-font-awesome
    - ttf-ms-fonts
    - ttf-wps-fonts

