- name: Install dotnet packages
  kewlfft.aur.aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - dotnet-sdk
    - dotnet-sdk-6.0
    - aspnet-runtime
    - aspnet-runtime-6.0
    - mono-msbuild

- name: Install Jetbrains packages
  kewlfft.aur.aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - rider
    - webstorm
    - datagrip
