- name: Install media-related packages
  kewlfft.aur.aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - alsa-firmware
    - handbrake

- name: Install pulseaudio
  kewlfft.aur.aur:
    name: "{{ item }}"
  become: true
  become_user: aur_builder
  loop:
    - alsa-utils
    - pavucontrol
    - pulseaudio
